# Generated by Django 4.2.16 on 2025-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='client',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='rental',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
